image: Visual Studio 2017
branches:
  only:
  - master
  - develop
  - /release\/.+/
install:
  - cinst gitversion.portable -y
  - ps: dotnet tool install --global dotnet-setversion
before_build:
  - nuget restore
  - ps: $env:VERSION=$(gitversion /showvariable NuGetVersionV2)
build_script:
  - ps: dotnet restore
  - ps: cd src/dotnet-setversion; setversion $env:VERSION; dotnet pack -c Release -o release/; cd ../..
before_test:
  - ps: cd test/integration;
test_script:
  - ps: dotnet test -c Release;
after_test:
  - ps: cd ../..
artifacts:
  path: src/dotnet-setversion/release/*.nupkg
  name: NuGet packages
deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: USCwZe1eILJaDmG30VFhlFWmr2P0G6o0HhUau72/W+TzyAMZyqEfL//vQhfjTSKP
  artifact: NuGet packages
  on:
    branch: master